### PR TITLE
[Payment] New slot pay menchanism

### LINKED ISSUE #153: [Payment] Transfer failed will cause wrong settlement for provider
If `maybe_transfer` failed, is that possible the *real payed amount* != *amount*? 
https://github.com/crustio/crust/blob/8e3dc7d996ad48f3e482b8749f5ec9275d4f0522/cstrml/payment/src/lib.rs#L173-L179

### LINKED ISSUE #158: [Payment] What if scheduler set failed

### PR DESCRIPTION
**Pull request by MyronFanQiu**
Fix #158 
Fix #153(Need check the menchanism)

- Remove schedular and use `on_initialize`
- Add new storage to stora slot pay
- Add regular batch transfer functionality
- Remove Clients
- Rename Payments and Ledger back to PaymentLedger

### CODE REVIEW

**Comment by zikunfan** [comment]
Can we resolve #178 in this pr?

File: cstrml/payment/src/lib.rs [hunk 1]
```diff
@@ -141,71 +141,84 @@ decl_module! {
...
+                    <Payments<T>>::mutate(&sorder_id, |ledger| {
+                        if let Some(l) = ledger {
+                            l.paid += real_amount;
+                        }
+                    });
+                    Self::deposit_event(RawEvent::PaymentSuccess(client));
+                } else {
+                    // 7. Reserve it back
+                    // TODO: Double check this behavior since it should be a workaround. Maybe a special status is better?
+                    let _ = T::Currency::reserve(&client, real_amount);
```
Comment (MyronFanQiu) [inline cstrml/payment/src/lib.rs:210]: This will cause the real time longer than duration. Should we extend duration? Better to have a new status for storage order.

File: cstrml/payment/src/lib.rs [hunk 2]
```diff
@@ -141,71 +141,84 @@ decl_module! {
...
-                            }
-                        });
-                        Self::deposit_event(RawEvent::PaymentSuccess(client));
-                    }
-                },
-                _ => {}
+                } else {
+                    // TODO: Deal with failure
+                }
+            } else {
```
Comment (MyronFanQiu) [inline cstrml/payment/src/lib.rs:168]: need close this storage order.

File: cstrml/payment/src/lib.rs [hunk 3]
```diff
@@ -25,11 +25,13 @@ use serde::{Deserialize, Serialize};
 
 // Crust runtime modules
 use primitives::{
-    constants::time::MINUTES
+    constants::time::MINUTES, BlockNumber
 };
 
 use market::{OrderStatus, MarketInterface, Payment};
 
+const FREQUENCY: BlockNumber = MINUTES;
```
Comment (zikunfan) [inline cstrml/payment/src/lib.rs:33]: Can we put this into `Trait`?

File: cstrml/payment/src/lib.rs [hunk 4]
```diff
@@ -55,27 +57,19 @@ impl<T: Trait> Payment<<T as system::Trait>::AccountId,
...
-                // TODO: What if returning an error?
-                let _ = T::Scheduler::schedule_named(
-                    sorder_id.encode(),
-                    <system::Module<T>>::block_number() + minute, // must have a delay
-                    Some((minute, slots)),
-                    HARD_DEADLINE,
-                    Call::slot_pay(sorder_id.clone(), slot_amount).into(),
-                );
+                // 3. Arrange this slot pay
+                let payment_factor = so.completed_on % FREQUENCY;
```
Comment (zikunfan) [inline cstrml/payment/src/lib.rs:71]: `slot_factor` looks more reasonable for me

File: cstrml/payment/src/lib.rs [hunk 5]
```diff
@@ -141,71 +136,84 @@ decl_module! {
...
+            let now = TryInto::<BlockNumber>::try_into(now).ok().unwrap();
+            Self::regular_batch_transfer(now % FREQUENCY);
+            // TODO: Calculate accurate weight.
+            0
+        }
+    }
+}
 
+impl<T: Trait> Module<T> {
+    pub fn regular_batch_transfer(payment_factor: BlockNumber) {
```
Comment (zikunfan) [inline cstrml/payment/src/lib.rs:150]: just named `batch_transfer`?

File: cstrml/payment/src/lib.rs (hunk 2 above)
Comment (zikunfan) [reply cstrml/payment/src/lib.rs:163]: Add `TODO`

File: cstrml/payment/src/lib.rs (hunk 1 above)
Comment (zikunfan) [reply cstrml/payment/src/lib.rs:205]: We can take current strategy, do nothing and keep this `TODO`, we will explain when #138 resolved.

File: cstrml/payment/src/lib.rs [hunk 6]
```diff
@@ -105,11 +95,11 @@ pub trait Trait: system::Trait {
     /// Used to calculate payment
     type CurrencyToBalance: Convert<BalanceOf<Self>, u64> + Convert<u64, BalanceOf<Self>>;
 
-    /// The Scheduler.
-    type Scheduler: ScheduleNamed<Self::BlockNumber, Self::Proposal>;
-
     /// Interface for interacting with a market module.
     type MarketInterface: MarketInterface<Self::AccountId, Self::Hash, BalanceOf<Self>>;
+
+    /// Minimum storage order duration
```
Comment (zikunfan) [inline cstrml/payment/src/lib.rs:101]: Comments not match

File: cstrml/payment/src/lib.rs [hunk 7]
```diff
@@ -118,6 +108,10 @@ decl_storage! {
         /// A mapping from storage order id to payment ledger info
         pub Payments get(fn payments):
```
Comment (zikunfan) [inline cstrml/payment/src/lib.rs:109]: Since this is a ledge in payment，considering just named *PaymentLedger*？

File: cstrml/payment/src/lib.rs [hunk 8]
```diff
@@ -118,6 +108,10 @@ decl_storage! {
...
         map hasher(twox_64_concat) T::Hash => Option<Ledger<BalanceOf<T>>>;
```
Comment (zikunfan) [inline cstrml/payment/src/lib.rs:110]: Since we have `StakingLedger`, we can rename back to `PaymentLedger` to help `apps` and `sdk` distinguish.

Comment (MyronFanQiu) [reply cstrml/payment/src/lib.rs:110]: Will rename them all to PaymentLedger/PaymentLedgers
