### PR TITLE
[MPoW] Fix updating stake limit on reporting works

### LINKED ISSUE #88: [GPoS] Active stake limit update should influent all validators
When someone report works, it will update their's stake limit, and this should influent all validator's stake limit.

### PR DESCRIPTION
**Pull request by gougougogol**
resolves #88

### CODE REVIEW

File: cstrml/tee/src/lib.rs [hunk 1]
```diff
@@ -370,13 +370,38 @@ impl<T: Trait> Module<T> {
...
         Reserved::put(total_reserved);
+        let total_workload = total_used + total_reserved;
 
-        // 5. Call `on_report_works` handler
-        T::Works::report_works(
-            &who,
-            used + reserved,
-            total_used + total_reserved,
-        );
+        // 5. Work report for every identity
```
Comment (LowEntropyBody) [inline cstrml/tee/src/lib.rs:375]: Update work report for every identity

File: cstrml/tee/src/lib.rs [hunk 2]
```diff
@@ -370,13 +370,38 @@ impl<T: Trait> Module<T> {
...
+                        let sorder =
+                            T::MarketInterface::maybe_get_sorder(order_id).unwrap_or_default();
+                        if sorder.order_status == OrderStatus::Success {
+                            Some((sorder.file_identifier, order_id.clone()))
+                        } else {
+                            None
+                        }
+                    })
+                    .collect();
+            }
```
Comment (zikunfan) [inline cstrml/tee/src/lib.rs:392]: We don't need this, cause we already calculated them before

File: cstrml/tee/src/lib.rs [hunk 3]
```diff
@@ -370,13 +370,38 @@ impl<T: Trait> Module<T> {
...
+        let total_workload = total_used + total_reserved;
 
-        // 5. Call `on_report_works` handler
-        T::Works::report_works(
-            &who,
-            used + reserved,
-            total_used + total_reserved,
-        );
+        // 5. Update work report for every identity
+        let workload_map: Vec<(T::AccountId, u128)> = <TeeIdentities<T>>::iter().map(|(controller, _)| {
```
Comment (zikunfan) [inline cstrml/tee/src/lib.rs:376]: Do not need iterate all identities, cause this only influent these contains work report

File: cstrml/tee/src/lib.rs [hunk 4]
```diff
@@ -370,13 +370,38 @@ impl<T: Trait> Module<T> {
...
+                        if sorder.order_status == OrderStatus::Success {
+                            Some((sorder.file_identifier, order_id.clone()))
+                        } else {
+                            None
+                        }
+                    })
+                    .collect();
+            }
+            // b. calculate controller's own reserved and used space
+            let (reserved, used) = Self::update_and_get_workload(&controller, &order_files, rs);
```
Comment (zikunfan) [inline cstrml/tee/src/lib.rs:394]: we do not need get this, cause this function **ONLY** be called in the new era with `update_identities`

File: cstrml/tee/src/lib.rs [hunk 5]
```diff
@@ -370,13 +370,16 @@ impl<T: Trait> Module<T> {
...
-        T::Works::report_works(
-            &who,
-            used + reserved,
-            total_used + total_reserved,
-        );
+        // 5. Update work report for every identity
+        for (controller, wr) in <WorkReports<T>>::iter() {
+            T::Works::report_works(
+                &controller,
+                (&wr.used + &wr.reserved) as u128,
```
Comment (zikunfan) [inline cstrml/tee/src/lib.rs:379]: remove `&` cause used and reserved is basic type

File: cstrml/tee/src/lib.rs [hunk 6]
```diff
@@ -370,13 +370,16 @@ impl<T: Trait> Module<T> {
...
-        // 5. Call `on_report_works` handler
-        T::Works::report_works(
-            &who,
-            used + reserved,
-            total_used + total_reserved,
-        );
+        // 5. Update work report for every identity
+        for (controller, wr) in <WorkReports<T>>::iter() {
+            T::Works::report_works(
+                &controller,
```
Comment (zikunfan) [inline cstrml/tee/src/lib.rs:378]: remove &

**Comment by zikunfan** [comment]
Congras for your 1st pr🎉
