### PR TITLE
[MPoW] Extend IdBonds limitation during upgrading process

### LINKED ISSUE #282: [MPoW] Upgrade would fail if length of IdBond reach to the MaxLimit

### PR DESCRIPTION
**Pull request by MyronFanQiu**
Fix #282

### CODE REVIEW

File: cstrml/swork/src/lib.rs [hunk 1]
```diff
@@ -252,7 +252,15 @@ decl_module! {
...
 
             // 3. Ensure `id_bonds` still available
-            ensure!((Self::id_bonds(&who).len() as u32) < T::MaxBondsLimit::get(), Error::<T>::ExceedBondsLimit);
+            let legal_bonds_count: u32 = Self::id_bonds(&who).iter().fold(0u32, |acc, pk| {
+                if let Some(code) = Self::identities(&pk) {
+                    if code == Self::code(){
+                       return acc + 1;
+                    }
+                }
+                0
```
Comment (zikunfan) [inline cstrml/swork/src/lib.rs:261]: 0?

**Review by zikunfan — CHANGES_REQUESTED** [review]

File: cstrml/swork/src/tests.rs [hunk 2]
```diff
@@ -1326,4 +1326,53 @@ fn bonds_limit_should_work() {
...
+                ),
+                DispatchError::Module {
+                    index: 0,
+                    error: 8,
+                    message: Some("ExceedBondsLimit"),
+                }
+            );
+
+            assert_ok!(Swork::upgrade(Origin::root(), hex::decode("0011").unwrap(), 500));
+            // TODO: Use success register info later. Fake the test for now.
```
Comment (zikunfan) [inline cstrml/swork/src/tests.rs:1360]: extra line

**Review by zikunfan — CHANGES_REQUESTED** [review]

**Review by zikunfan — APPROVED** [review]

**Review by yuhui1208 — APPROVED** [review]
