### PR TITLE
[Market] Decrease order counts for wrong file size order

### LINKED ISSUE #764: Decrease the files count for dynamic base fee for illegalFileClosed

### PR DESCRIPTION
**Pull request by mmyyrroonn**
Fix #764

### CODE REVIEW

File: cstrml/market/src/lib.rs [hunk 1]
```diff
@@ -1025,6 +1025,7 @@ impl<T: Config> Module<T> {
                     }
                     <Files<T>>::remove(cid);
                     FileKeysCount::mutate(|count| *count = count.saturating_sub(1));
+                    OrdersCount::mutate(|count| {*count = count.saturating_sub(1)});
```
Comment (badkk) [inline cstrml/market/src/lib.rs:1028]: What if orders in (`22-622`) which contains wrong order but did not report before `622`. You still count the number right?

**Review by badkk — APPROVED** [review]
